name: ProudCitizen CI/CD Pipeline


on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "main" ]

env:
  ACR_NAME: proudcitizenacr  # Change this to your ACR name
  FRONTEND_APP: proudcitizen-frontend-app
  BACKEND_APP: proudcitizen-backend-app
  RESOURCE_GROUP: proudcitizen-rg
  LOCATION: East US 2

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
        working-directory: ./backend
      - run: npm run lint
        working-directory: ./backend
      - run: npm test
        working-directory: ./backend
      - name: Run dependency vulnerability scan
        run: npm audit --production
        working-directory: ./backend

  frontend-checks:
    runs-on: ubuntu-latest
    needs: backend-checks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
        working-directory: ./frontend
      - run: npm run build
        working-directory: ./frontend
      - run: npm run lint
        working-directory: ./frontend
      - name: Run dependency vulnerability scan
        run: npm audit --production
        working-directory: ./frontend

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [backend-checks, frontend-checks]
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Login to ACR
      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/proud-citizen-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push backend
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/proud-citizen-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Security scanning
      - name: Install Trivy
        run: |
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan frontend image
        run: |
          trivy image --exit-code 1 --severity CRITICAL ${{ env.ACR_NAME }}.azurecr.io/proud-citizen-frontend:${{ github.sha }}

      - name: Scan backend image
        run: |
          trivy image --exit-code 1 --severity CRITICAL ${{ env.ACR_NAME }}.azurecr.io/proud-citizen-backend:${{ github.sha }}

      # Deploy to Azure Container Apps
      - name: Deploy Frontend
        run: |
          az containerapp update \
            --name ${{ env.FRONTEND_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/proud-citizen-frontend:${{ github.sha }} \
            --registry-server ${{ env.ACR_NAME }}.azurecr.io \
            --query properties.configuration.ingress.fqdn

      - name: Deploy Backend
        run: |
          az containerapp update \
            --name ${{ env.BACKEND_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/proud-citizen-backend:${{ github.sha }} \
            --registry-server ${{ env.ACR_NAME }}.azurecr.io